name: test

on:
  push:

jobs:
  echo-to-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "test" >> README.md
          git add README.md
          git commit -m "test"