name: test

on:
  push:

jobs:
  echo-to-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: save current tag
        run: echo $GITHUB_REF > .github/tag.txt
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add .github/tag.txt
          git commit -m "new commit message"
          git push origin main